### ISSUE TITLE
Right click option

### ISSUE THREAD

**Issue by danbp** [imath/bp-bookmarklet#4]
usually, a link can be opened by using right-click > open in a new window. This doesn't happen whith Bookmarklet. Precisely, when a picture is linked. (see http://bp-fr.net/membres/dan/activity/22980/)

Also, when more than one bookmarklet is published on the SWA, only the first one use a picture excerpt. The second is in full text. Is this intended ?

**Comment by imath** [comment]
Thanks for the feedback, will look at it asap.

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
Here's the situation, you have 2 kind of bookmarklets:
1. embeds
2. outputs from the plugin

In the first case, it's often an iframe and the embed provider can force all links to open into the '_top' target, meaning replace the current page. This is what's happening for instance when you embed a WordPress post.

In the second case, right clicking will work.

So you can use this snippet to add a button to open the link into a new window:

``` php
function dan_open_in_new_window_button() {
    if ( 'bookmark_published' !== bp_get_activity_type() ) {
        return;
    }

    $bookmarklet = bp_activity_get_meta( bp_get_activity_id(), '_bookmarklet_data' );

    if ( is_object( $bookmarklet ) ) {
        $url = $bookmarklet->url;
    } else {
        $url = $bookmarklet;
    }

    printf( '<a href="%s" class="button bp-secondary-action" target="_blank" title="Open in new window">Open in new window</a>',
        esc_url( $url )
    );
}
add_action( 'bp_activity_entry_meta', 'dan_open_in_new_window_button' );
```

Now about 

> Also, when more than one bookmarklet is published on the SWA, only the first one use a picture excerpt. The second is in full text. Is this intended ?

I wasn't able to reproduce. I guess this is part of mysterious things :) As you can see all embeds are displaying an image + excerpt:

![seems-ok](https://cloud.githubusercontent.com/assets/1834524/15493372/fb04ac3a-2183-11e6-9552-6ece39ca0387.png)
